apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "wiki.fullname" . }}-pdf
  labels:
    app.kubernetes.io/name: {{ include "wiki.name" . }}-pdf
    helm.sh/chart: {{ include "wiki.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.pdf.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wiki.name" . }}-pdf
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wiki.name" . }}-pdf
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-pdf
          image: "{{ .Values.pdf.image.repository }}:{{ .Values.pdf.image.tag }}"
          imagePullPolicy: {{ .Values.pdf.image.pullPolicy }}
          ports:
            - name: pdf
              containerPort: 3000
              protocol: TCP
          env:
          - name: "HOSTNAME"
            value: ""
          - name: "CONCURRENCY"
            value: "1"
          - name: "TIMEOUT"
            value: "30"
          - name: "WINDOW_WIDTH"
            value: {{ .Values.pdf.window.width }}
          - name: "WINDOW_HEIGHT"
            value: {{ .Values.pdf.window.height }}
          - name: "PORT"
            value: "3000"
          livenessProbe:
            httpGet:
              path: /
              port: pdf
          readinessProbe:
            httpGet:
              path: /
              port: pdf
          resources:
{{ toYaml .Values.pdf.resources | indent 12 }}
    {{- with .Values.pdf.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.pdf.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.pdf.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
