apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "wiki.fullname" . }}"
  labels:
    app: {{ template "wiki.name" . }}
    chart: {{ template "wiki.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Values.pdf.secret }}
  pdf-secret: {{ .Values.pdf.secret | b64enc | quote }}
{{ else }}
  pdf-secret: {{ randAlphaNum 10 | b64enc | quote }}
{{- end -}}
{{- if .Values.mariadb.user }}
  db-user: {{ .Values.mariadb.user | b64enc | quote }}
{{- if .Values.mariadb.password }}
  db-password: {{ .Values.mariadb.password | b64enc | quote }}
{{ else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end -}}
{{- end -}}